### ISSUE TITLE
conflict/clash with `factoryboy==3.2.0`

### ISSUE THREAD

**Issue by skarzi** [pytest-dev/pytest-factoryboy#107]
Hi :wave: 

First of all thanks for maintaining this great project!

`pytest-factoryboy` no longer works with `factoryboy==3.2.0`, following exception is raised inside [`model_fixture`](https://github.com/pytest-dev/pytest-factoryboy/blob/1601cb794c703d6f6d442ae1ab674cbb973e1055/pytest_factoryboy/fixture.py#L246):

```
AttributeError: module 'factory.builder' has no attribute 'PostGenerationContext'
```

It's related to https://github.com/FactoryBoy/factory_boy/pull/828

This issue also shows that we need to add some env to `tox` with tests ran for `factoryboy` built from `master` branch, just to know that something could potentially break in the next release

**Comment by youtux** [comment]
Fixed by https://github.com/pytest-dev/pytest-factoryboy/pull/109

**Comment by youtux** [comment]
I just released version 2.1.0 that contains the fix for this issue.
